type MaterialOptions = {
  color?: ColorRepresentation | undefined;
  opacity?: number | undefined;
  map?: Texture | null | undefined;
  lightMap?: Texture | null;
  lightMapIntensity?: number | undefined;
  aoMap?: Texture | null | undefined;
  aoMapIntensity?: number | undefined;
  specularMap?: Texture | null | undefined;
  alphaMap?: Texture | null | undefined;
  fog?: boolean | undefined;
  envMap?: Texture | null | undefined;
  envMapRotation?: Euler | undefined;
  combine?: Combine | undefined;
  reflectivity?: number | undefined;
  refractionRatio?: number | undefined;
  wireframe?: boolean | undefined;
  wireframeLinewidth?: number | undefined;
  wireframeLinecap?: string | undefined;
  wireframeLinejoin?: string | undefined;
  alphaHash?: boolean | undefined;
  alphaTest?: number | undefined;
  alphaToCoverage?: boolean | undefined;
  blendAlpha?: number | undefined;
  blendColor?: ColorRepresentation | undefined;
  blendDst?: BlendingDstFactor | undefined;
  blendDstAlpha?: number | undefined;
  blendEquation?: BlendingEquation | undefined;
  blendEquationAlpha?: number | undefined;
  blending?: Blending | undefined;
  blendSrc?: BlendingSrcFactor | BlendingDstFactor | undefined;
  blendSrcAlpha?: number | undefined;
  clipIntersection?: boolean | undefined;
  clippingPlanes?: Plane[] | undefined;
  clipShadows?: boolean | undefined;
  colorWrite?: boolean | undefined;
  depthFunc?: DepthModes | undefined;
  depthTest?: boolean | undefined;
  depthWrite?: boolean | undefined;
  name?: string | undefined;
  opacity?: number | undefined;
  polygonOffset?: boolean | undefined;
  polygonOffsetFactor?: number | undefined;
  polygonOffsetUnits?: number | undefined;
  precision?: "highp" | "mediump" | "lowp" | null | undefined;
  premultipliedAlpha?: boolean | undefined;
  forceSinglePass?: boolean | undefined;
  dithering?: boolean | undefined;
  side?: Side | undefined;
  shadowSide?: Side | undefined;
  toneMapped?: boolean | undefined;
  transparent?: boolean | undefined;
  vertexColors?: boolean | undefined;
  visible?: boolean | undefined;
  format?: PixelFormat | undefined;
  stencilWrite?: boolean | undefined;
  stencilFunc?: StencilFunc | undefined;
  stencilRef?: number | undefined;
  stencilWriteMask?: number | undefined;
  stencilFuncMask?: number | undefined;
  stencilFail?: StencilOp | undefined;
  stencilZFail?: StencilOp | undefined;
  stencilZPass?: StencilOp | undefined;
}